# Audit all gems listed in the Gemfile for known security problems by running bin/bundler-audit.
# CVEs that are not relevant to the application can be enumerated on the ignore list below.

ignore:
  - GHSA-53p3-c7vp-4mcc
  - GHSA-qmpg-8xg6-ph5q
  - CVE-2026-33658
  - GHSA-p9fm-f462-ggrg
  - CVE-2026-33210
  - GHSA-3m6g-2423-7cp3
  - GHSA-46fp-8f5p-pf2m
  - CVE-2026-33946
  - GHSA-qvqr-5cv7-wh35
